FROM debian:9

RUN apt-get update -qq && \
    apt-get install -qq sudo python-apt python-pycurl python-pip python-dev \
                        libffi-dev && \
    pip install -U setuptools && \
    pip install -q ansible==2.5.2

    WORKDIR /tmp/ansible-role-mtproxy
    COPY  .  /tmp/ansible-role-mtproxy

    RUN echo localhost > inventory
    RUN ansible-playbook -i inventory -c local tests/playbook.yml

    RUN crontab -l
    RUN cat /etc/systemd/system/mtproxy.service
