FROM centos:7

RUN yum -y install epel-release && \
    yum -y install sudo python python-devel python-pip \
     initscripts libffi-devel && \
    pip install -q cffi && \
    pip install -q ansible==2.5.2

WORKDIR /tmp/ansible-role-mtproxy
COPY  .  /tmp/ansible-role-mtproxy

RUN echo localhost > inventory
RUN ansible-playbook -i inventory -c local tests/playbook.yml

RUN crontab -l
RUN cat /etc/systemd/system/mtproxy.service
